// auto-generated
// Code generated by '$ fyne bundle'. DO NOT EDIT.

package main

import (
	_ "embed"
	"fyne.io/fyne/v2"
)

//go:embed icon.svg
var iconResourceData []byte
var iconResource = &fyne.StaticResource{
	StaticName:    "icon.svg",
	StaticContent: iconResourceData,
}
